site_name: OpenS Suite Documentation

theme:
  logo: launcher.png

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google

  - Home: index.md
  - Shortcuts: shortcuts.md
  - API Reference: api.md
  - Calculator: calculator.md

