site_name: OpenS Suite Documentation

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google

nav:
  - Home: index.md
